#!/usr/bin/env ruby

require "wardite"

path = ARGV[0]
method = ARGV[1]
args = ARGV[2..-1] || []

f = File.open(path)
instance = Wardite::BinaryLoader::load_from_buffer(f);
if !method && instance.runtime.respond_to?(:_start)
  instance.runtime._start
else
  ret = instance.runtime.call(method, args)
  $stderr.puts "return value: #{ret.inspect}"
end