name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.9'
          - '3.4.5'
        wasm_tools:
          - '1.236.0'
        hyperfine:
          - '1.19.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install wasm-tools
      run: |
        mkdir -p $HOME/.bin
        curl -L https://github.com/bytecodealliance/wasm-tools/releases/download/v${{ matrix.wasm_tools }}/wasm-tools-${{ matrix.wasm_tools }}-x86_64-linux.tar.gz -o wasm-tools.tar.gz
        tar xvzf wasm-tools.tar.gz
        mv wasm-tools-*-x86_64-linux/wasm-tools $HOME/.bin/wasm-tools
        chmod a+x $HOME/.bin/wasm-tools
        echo "$HOME/.bin" >> $GITHUB_PATH
    - name: Install Hyperfine
      run: |
        HYPERFINE_VERSION="${{ matrix.hyperfine }}"
        curl -LO "https://github.com/sharkdp/hyperfine/releases/download/v${HYPERFINE_VERSION}/hyperfine-v${HYPERFINE_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        tar xzf "hyperfine-v${HYPERFINE_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
        mkdir -p $HOME/.bin
        mv "hyperfine-v${HYPERFINE_VERSION}-x86_64-unknown-linux-gnu/hyperfine" $HOME/.bin/hyperfine
        chmod a+x $HOME/.bin/hyperfine
    - name: Version wasm-tools
      run: |
        wasm-tools --version
    - name: Version Hyperfine
      run: |
        hyperfine --version
    - name: Run the bench task
      run: |
        bundle exec rake basic_benchmark
