name: Test Wardite

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.9'
          - '3.4.5'
        wasm_tools:
          - '1.236.0'
        wabt:
          - '1.0.37'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install wasm-tools
      run: |
        mkdir -p $HOME/.bin
        curl -L https://github.com/bytecodealliance/wasm-tools/releases/download/v${{ matrix.wasm_tools }}/wasm-tools-${{ matrix.wasm_tools }}-x86_64-linux.tar.gz -o wasm-tools.tar.gz
        tar xvzf wasm-tools.tar.gz
        mv wasm-tools-*-x86_64-linux/wasm-tools $HOME/.bin/wasm-tools
        chmod a+x $HOME/.bin/wasm-tools
        echo "$HOME/.bin" >> $GITHUB_PATH
    - name: Version wasm-tools
      run: |
        wasm-tools --version
    - name: Install wast2json
      run: |
        mkdir -p $HOME/.bin
        curl -L https://github.com/WebAssembly/wabt/releases/download/${{ matrix.wabt }}/wabt-${{ matrix.wabt }}-ubuntu-20.04.tar.gz -o wabt.tar.gz
        tar xvzf wabt.tar.gz
        mv wabt-*/bin/wast2json $HOME/.bin/wast2json
        chmod a+x $HOME/.bin/wast2json
    - name: Version wast2json
      run: |
        wast2json --version
    - name: Run the check task
      run: |
        bundle exec rake check
    - name: Run the test task
      run: |
        bundle exec rake test
    - name: Run the official spec
      run: |
        bundle exec rake 'spec[i32]'
