name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.4'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install wasm-tools
      run: |
        mkdir .bin
        curl -L https://github.com/bytecodealliance/wasm-tools/releases/download/v1.221.2/wasm-tools-1.221.2-x86_64-linux.tar.gz -o wasm-tools.tar.gz
        tar xvzf wasm-tools.tar.gz
        mv wasm-tools-*-x86_64-linux/wasm-tools .bin/wasm-tools
        chmod a+x .bin/wasm-tools
    - name: Version wasm-tools
      run: |
        export PATH=`pwd`/.bin:$PATH
        wasm-tools --version
    - name: Run the check task
      run: |
        export PATH=`pwd`/.bin:$PATH
        bundle exec rake check
        - name: Run the test task
        run: |
          export PATH=`pwd`/.bin:$PATH
          bundle exec rake test
